name = "worker_www_typescript"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-14"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
upstream = ""
# cache = true
# cache_persist = "./cache"

[miniflare.https]
key = ""
cert = ""

[env.test]
zone_id = ""
route = ""